name: Theme Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: easolhq/theme-upload@1.0.0-alpha
        env:
          EASOL_KEY: ${{ secrets.EASOL_KEY }}
          EASOL_SECRET: ${{ secrets.EASOL_SECRET }}
          THEME_KEY: 'studio'
